### ISSUE TITLE
Ethernet servo cable

### ISSUE THREAD

**Issue by pdxaeroman** [LaSalleRobots/PowerPlay#26]
Demo>purchase>create

**Comment by pdxaeroman** [comment]
Problems with this. I got it to 100% function once but there seems to be glitch happening. Maybe servos drawing too much current for cable after all. Maybe wiring is not ideal. Needs fix

**Comment by pdxaeroman** [comment]
And not kidding, this needs to be fixed before next meet because we cannot go back to that janky retractor design lol

**Comment by lukasmwerner** [comment]
we did it and it works but it is maybe we should just use a custom retractable cable?

**Comment by pdxaeroman** [comment]
Hey what about a wind up car motor? To turn the spool
