### ISSUE TITLE
Mecanum Drive Encoders

### ISSUE THREAD

**Issue by lukasmwerner** [LaSalleRobots/PowerPlay#6]
We want to be able to use the encoders from the motors to track where we are going to get a distance based driving implementation.

**Comment by pdxaeroman** [comment]
Could this also achieve passive measurement in analog control?

**Comment by lukasmwerner** [comment]
yeah should be able to. but not sure how much it would help. we would need to back translate the encoder info over time to find out where we are going based on where we were.
